# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import datetime
from django.utils.timezone import utc
from django.conf import settings
import rnoc.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BCNOSS',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object', models.CharField(max_length=50, verbose_name='\u0110\u1ed1i t\u01b0\u1ee3ng')),
                ('gio_mat', models.DateTimeField(verbose_name='gi\u1edd m\u1ea5t')),
                ('gio_tot', models.DateTimeField(null=True, verbose_name='gi\u1edd t\u1ed1t', blank=True)),
                ('code_loi', models.IntegerField()),
                ('vnp_comment', models.CharField(max_length=500)),
                ('gio_canh_bao_ac', models.DateTimeField(null=True, verbose_name='gi\u1edd canh bao AC', blank=True)),
                ('tong_thoi_gian', models.IntegerField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BSCRNC',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=50)),
                ('HANG_SX', models.CharField(max_length=20, null=True, blank=True)),
                ('DIA_CHI', models.CharField(max_length=200, null=True, blank=True)),
                ('DIEN_THOAI', models.CharField(max_length=20, null=True, blank=True)),
                ('TINH_RNC_QUAN_LY', models.CharField(max_length=50, null=True, blank=True)),
                ('MSS', models.CharField(max_length=20, null=True, blank=True)),
                ('SGSN', models.CharField(max_length=20, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BTSType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CaTruc',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=30)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_catruc_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('datetime', models.DateTimeField(verbose_name='nh\u1eadp gi\u1edd', blank=True)),
                ('comment', models.CharField(max_length=2000, null=True, blank=True)),
                ('ngay_gio_tao', models.DateTimeField(verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoiTac',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True, blank=True)),
                ('Don_vi', models.CharField(max_length=80, null=True, verbose_name='\u0110\u01a1n V\u1ecb', blank=True)),
                ('So_dien_thoai', models.CharField(max_length=80, null=True, verbose_name='S\u1ed1 \u0111i\u1ec7n tho\u1ea1i', blank=True)),
                ('Nam_sinh', models.CharField(max_length=80, null=True, verbose_name='N\u0103m Sinh', blank=True)),
                ('email', models.CharField(max_length=80, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=80, null=True, verbose_name='Ghi ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 986150), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_doitac_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_doitac_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DuAn',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=150)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True)),
                ('ghi_chu', models.CharField(max_length=1330, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('type_2G_or_3G', models.CharField(max_length=2, blank=True)),
                ('thoi_diem_bat_dau', models.DateTimeField(null=True, verbose_name='th\u1eddi \u0111i\u1ec3m b\u1eaft \u0111\u1ea7u', blank=True)),
                ('thoi_diem_ket_thuc', models.DateTimeField(null=True, verbose_name='th\u1eddi \u0111i\u1ec3m k\u1ebft th\xfac', blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 987465), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('doi_tac_du_an', models.ManyToManyField(to='rnoc.DoiTac', null=True, verbose_name='\u0110\u1ed1i t\xe1c d\u1ef1 \xe1n', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_duan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_duan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('modal_name', models.CharField(max_length=50)),
                ('edited_object_id', models.IntegerField()),
                ('ly_do_sua', models.CharField(max_length=250)),
                ('edit_datetime', models.DateTimeField(null=True, blank=True)),
                ('thanh_vien', models.ForeignKey(verbose_name='Th\xe0nh vi\xean s\u1eeda', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultLibrary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=100)),
                ('diversity', models.CharField(max_length=10, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 995910), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_FaultLibrary_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_FaultLibrary_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lenh',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('command', models.CharField(unique=True, max_length=5000)),
                ('Name', models.CharField(max_length=200, null=True, blank=True)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True, blank=True)),
                ('ghi_chu_lenh', models.CharField(max_length=200, null=True, verbose_name='Ghi ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 997016), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_Lenh_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_Lenh_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mll',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object', models.CharField(max_length=50, verbose_name='\u0110\u1ed1i t\u01b0\u1ee3ng')),
                ('site_name', models.CharField(max_length=50, null=True, verbose_name='Site name', blank=True)),
                ('ung_cuu', models.BooleanField(default=False, verbose_name='\u01b0/c')),
                ('gio_mat', models.DateTimeField(verbose_name='gi\u1edd m\u1ea5t', blank=True)),
                ('gio_tot', models.DateTimeField(null=True, verbose_name='gi\u1edd t\u1ed1t', blank=True)),
                ('giao_ca', models.BooleanField(default=False, verbose_name='g/ca')),
                ('nghiem_trong', models.BooleanField(default=False, verbose_name='N/tr\u1ecdng')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 28, 8110), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('ca_truc', models.ForeignKey(verbose_name='Ca tr\u1ef1c', blank=True, to='rnoc.CaTruc', null=True)),
                ('du_an', models.ForeignKey(related_name='DuAns', verbose_name='d\u1ef1 \xe1n/c\xf4ng vi\u1ec7c', blank=True, to='rnoc.DuAn', null=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_mll_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_mlll_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NguyenNhan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=150)),
                ('Name_khong_dau', models.CharField(max_length=150, null=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 7, 3, 27, 991296, tzinfo=utc), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_NguyenNhan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_NguyenNhan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuanHuyen',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('query_string', models.CharField(max_length=200, null=True, blank=True)),
                ('search_datetime', models.DateTimeField(null=True, blank=True)),
                ('thanh_vien', models.ForeignKey(blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificProblem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('object_name', models.CharField(max_length=200, null=True, blank=True)),
                ('fault', models.ForeignKey(blank=True, to='rnoc.FaultLibrary', null=True)),
                ('mll', models.ForeignKey(related_name='specific_problems', to='rnoc.Mll')),
            ],
        ),
        migrations.CreateModel(
            name='SuCo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=150)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 7, 3, 27, 990185, tzinfo=utc), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_nguyennhan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_nguyennhan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThaoTacLienQuan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=100)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('Name_khong_dau', models.CharField(max_length=100, null=True)),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 994849), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_ThaoTacLienQuan_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_ThaoTacLienQuan_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThietBi',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=20, null=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, blank=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('is_duoc_tao_truoc', models.BooleanField(verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 984921), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('bts_type', models.ForeignKey(to='rnoc.BTSType', null=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_thietbi_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_thietbi_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tinh',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=50)),
                ('Name_khong_dau', models.CharField(unique=True, max_length=50, blank=True)),
                ('dia_ban', models.CharField(max_length=80, verbose_name='\u0110\u1ecba b\xe0n')),
                ('ma_tinh', models.CharField(unique=True, max_length=4)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_Tinh_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tram',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('License_60W_Power', models.NullBooleanField()),
                ('U900', models.NullBooleanField()),
                ('Site_ID_3G', models.CharField(max_length=80, null=True, blank=True)),
                ('Ngay_Phat_Song_2G', models.DateField(null=True, verbose_name='Ng\xe0y ph\xe1t s\xf3ng 2G', blank=True)),
                ('Ngay_Phat_Song_3G', models.DateField(null=True, verbose_name='Ng\xe0y ph\xe1t s\xf3ng 3G', blank=True)),
                ('Site_Name_1', models.CharField(max_length=80, null=True)),
                ('Site_Name_2', models.CharField(max_length=80, null=True, blank=True)),
                ('Status', models.CharField(max_length=50, null=True, blank=True)),
                ('Project_Text', models.CharField(max_length=100, null=True, blank=True)),
                ('Trans', models.CharField(max_length=40, null=True, blank=True)),
                ('Port', models.CharField(max_length=40, null=True, blank=True)),
                ('IUB_VLAN_ID', models.CharField(max_length=4, null=True, blank=True)),
                ('IUB_SUBNET_PREFIX', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('IUB_DEFAULT_ROUTER', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('IUB_HOST_IP', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_VLAN_ID', models.CharField(max_length=4, null=True, blank=True)),
                ('MUB_SUBNET_PREFIX', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_DEFAULT_ROUTER', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('MUB_HOST_IP', rnoc.models.IPAddress_FieldNullable(null=True, blank=True)),
                ('ghi_chu_tram', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('import_ghi_chu', models.CharField(max_length=400, null=True, blank=True)),
                ('dia_chi_3G', models.CharField(max_length=200, null=True, verbose_name='\u0110\u1ecba ch\u1ec9 2G', blank=True)),
                ('Cell_1_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_2_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_3_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_4_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_5_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_6_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_7_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_8_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_9_Site_remote', models.CharField(max_length=40, null=True, blank=True)),
                ('Cell_K_U900_PSI', models.CharField(max_length=40, null=True, blank=True)),
                ('dia_chi_2G', models.CharField(max_length=200, null=True, verbose_name='\u0110\u1ecba ch\u1ec9 2G', blank=True)),
                ('Site_ID_2G', models.CharField(max_length=80, null=True, blank=True)),
                ('Site_ID_2G_Number', models.CharField(max_length=10, null=True, blank=True)),
                ('LAC_2G', models.CharField(max_length=20, null=True, blank=True)),
                ('Nha_Tram', models.CharField(max_length=20, null=True, verbose_name='Nh\xe0 Tr\u1ea1m', blank=True)),
                ('Ma_Tram_DHTT', models.CharField(max_length=20, null=True, verbose_name='M\xe3 tr\u1ea1m \u0110HTT', blank=True)),
                ('Cell_ID_2G', models.CharField(max_length=20, null=True, blank=True)),
                ('cau_hinh_2G', models.CharField(max_length=20, null=True, verbose_name='C\u1ea5u h\xecnh 2G', blank=True)),
                ('TG_Text', models.CharField(max_length=150, null=True, blank=True)),
                ('TG', models.CharField(max_length=3, null=True, blank=True)),
                ('TG_1800', models.CharField(max_length=3, null=True, blank=True)),
                ('Long_3G', models.CharField(max_length=30, null=True, blank=True)),
                ('Lat_3G', models.CharField(max_length=30, null=True, blank=True)),
                ('Long_2G', models.CharField(max_length=30, null=True, blank=True)),
                ('Lat_2G', models.CharField(max_length=30, null=True, blank=True)),
                ('TRX_DEF', models.CharField(max_length=50, null=True, blank=True)),
                ('ntpServerIpAddressPrimary', models.CharField(max_length=20, null=True, blank=True)),
                ('ntpServerIpAddressSecondary', models.CharField(max_length=20, null=True, blank=True)),
                ('ntpServerIpAddress1', models.CharField(max_length=20, null=True, blank=True)),
                ('ntpServerIpAddress2', models.CharField(max_length=20, null=True, blank=True)),
                ('eNodeB_Name', models.CharField(max_length=40, null=True, blank=True)),
                ('eNodeB_ID_DEC', models.CharField(max_length=6, null=True, blank=True)),
                ('is_co_U900_rieng', models.NullBooleanField(default=False, verbose_name='Site 3G c\xf3 Site U900 ri\xeang')),
                ('is_co_U2100_rieng', models.NullBooleanField(default=False, verbose_name='Site 3G c\xf3 Site U2100 ri\xeang')),
                ('active_3G', models.BooleanField(default=False, verbose_name='\u0110ang Active 3G')),
                ('active_2G', models.BooleanField(default=False, verbose_name='\u0110ang Active 2G')),
                ('active_4G', models.BooleanField(default=False, verbose_name='\u0110ang Active 4G')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 7, 3, 28, 3736, tzinfo=utc), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('BSC_2G', models.ForeignKey(related_name='bscrnc_dot_Tram_BSC_2G_set', blank=True, to='rnoc.BSCRNC', null=True)),
                ('Cabinet', models.ForeignKey(related_name='Tramcuathietbis', verbose_name='Thi\u1ebft b\u1ecb 3G', blank=True, to='rnoc.ThietBi', null=True)),
                ('RNC', models.ForeignKey(blank=True, to='rnoc.BSCRNC', null=True)),
                ('Site_type', models.ForeignKey(to='rnoc.SiteType')),
            ],
        ),
        migrations.CreateModel(
            name='TrangThai',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(unique=True, max_length=100)),
                ('Name_khong_dau', models.CharField(max_length=80, null=True)),
                ('ghi_chu', models.CharField(max_length=10000, null=True, verbose_name='Ghi Ch\xfa', blank=True)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('is_cap_nhap_gio_tot', models.BooleanField()),
                ('is_duoc_tao_truoc', models.BooleanField(default=False, verbose_name='Kh\xf4ng cho ph\xe9p s\u1eeda field Name')),
                ('ngay_gio_tao', models.DateTimeField(default=datetime.datetime(2016, 5, 27, 2, 3, 27, 993393), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o', blank=True)),
                ('ngay_gio_sua', models.DateTimeField(null=True, verbose_name='Ng\xe0y gi\u1edd s\u1eeda cu\u1ed1i c\xf9ng', blank=True)),
                ('ly_do_sua', models.CharField(max_length=100, verbose_name='L\xfd do s\u1eeda', blank=True)),
                ('nguoi_sua_cuoi_cung', models.ForeignKey(related_name='user_nguoi_sua_dot_trangthai_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True)),
                ('nguoi_tao', models.ForeignKey(related_name='user_nguoi_tao_dot_trangthai_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UPE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('Name', models.CharField(max_length=80)),
                ('tinh', models.ForeignKey(related_name='Tinh_dot_UPE_sets', to='rnoc.Tinh')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('color_code', models.CharField(max_length=15, null=True, blank=True)),
                ('khong_search_tu_dong', models.BooleanField(default=True, verbose_name='Kh\xf4ng search t\u1ef1 \u0111\u1ed9ng \u0111\u1ed1i v\u1edbi table MLL')),
                ('khong_search_tu_dong_tram', models.BooleanField(default=True, verbose_name='Kh\xf4ng search t\u1ef1 \u0111\u1ed9ng Tr\u1ea1m')),
                ('ca_truc', models.ForeignKey(to='rnoc.CaTruc', null=True)),
                ('loc_ca', models.ManyToManyField(related_name='catruc_dot_userprofile_dot_set', to='rnoc.CaTruc', blank=True)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tram',
            name='UPE',
            field=models.ForeignKey(blank=True, to='rnoc.UPE', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='du_an',
            field=models.ManyToManyField(to='rnoc.DuAn', null=True, verbose_name='D\u1ef1 \xe1n', blank=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='eNodeB_Type',
            field=models.ForeignKey(related_name='ThietBi_of_eNodeB', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='nguoi_sua_cuoi_cung',
            field=models.ForeignKey(related_name='user_nguoi_sua_dot_tram_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='nguoi_tao',
            field=models.ForeignKey(related_name='user_nguoi_tao_dot_tram_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tram',
            name='nha_san_xuat_2G',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb 2G', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='quan_huyen',
            field=models.ForeignKey(verbose_name='Qu\u1eadn huy\u1ec7n', blank=True, to='rnoc.QuanHuyen', null=True),
        ),
        migrations.AddField(
            model_name='tram',
            name='tinh',
            field=models.ForeignKey(verbose_name='T\u1ec9nh', blank=True, to='rnoc.Tinh', null=True),
        ),
        migrations.AddField(
            model_name='quanhuyen',
            name='tinh',
            field=models.ForeignKey(related_name='Tinh_dot_quan_huyen_sets', to='rnoc.Tinh'),
        ),
        migrations.AddField(
            model_name='mll',
            name='nguyen_nhan',
            field=models.ForeignKey(related_name='mll_set_of_NguyenNhan', verbose_name='Nguy\xean nh\xe2n', blank=True, to='rnoc.NguyenNhan', null=True),
        ),
        migrations.AddField(
            model_name='mll',
            name='su_co',
            field=models.ForeignKey(related_name='Mlls', verbose_name='S\u1ef1 c\u1ed1', blank=True, to='rnoc.SuCo', null=True),
        ),
        migrations.AddField(
            model_name='mll',
            name='thiet_bi',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='mll',
            name='trang_thai',
            field=models.ForeignKey(verbose_name='Tr\u1ea1ng th\xe1i', blank=True, to='rnoc.TrangThai', null=True),
        ),
        migrations.AddField(
            model_name='lenh',
            name='thiet_bi',
            field=models.ForeignKey(verbose_name='Thi\u1ebft b\u1ecb', blank=True, to='rnoc.ThietBi', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='doi_tac',
            field=models.ForeignKey(related_name='Comments', verbose_name='\u0111\u1ed1i t\xe1c', blank=True, to='rnoc.DoiTac', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='mll',
            field=models.ForeignKey(related_name='comments', blank=True, to='rnoc.Mll'),
        ),
        migrations.AddField(
            model_name='comment',
            name='nguoi_sua_cuoi_cung',
            field=models.ForeignKey(related_name='user_nguoi_sua_dot_comment_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='nguoi_tao',
            field=models.ForeignKey(related_name='user_nguoi_tao_dot_comment_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='thao_tac_lien_quan',
            field=models.ManyToManyField(to='rnoc.ThaoTacLienQuan', null=True, blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='trang_thai',
            field=models.ForeignKey(verbose_name='Tr\u1ea1ng th\xe1i', blank=True, to='rnoc.TrangThai'),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='VI_TRI_RNC',
            field=models.ForeignKey(to='rnoc.Tinh', null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='nguoi_sua_cuoi_cung',
            field=models.ForeignKey(related_name='user_nguoi_sua_dot_BSCRNC_set', verbose_name='ng\u01b0\u1eddi s\u1eeda cu\u1ed1i c\xf9ng', blank=True, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='bscrnc',
            name='nguoi_tao',
            field=models.ForeignKey(related_name='user_nguoi_tao_dot_BSCRNC_set', verbose_name='Ng\u01b0\u1eddi t\u1ea1o', blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='BSC_or_RNC',
            field=models.ForeignKey(blank=True, to='rnoc.BSCRNC', null=True),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='BTS_Type',
            field=models.ForeignKey(verbose_name='2G,3G or 4G', blank=True, to='rnoc.BTSType', null=True),
        ),
        migrations.AddField(
            model_name='bcnoss',
            name='BTS_thiet_bi',
            field=models.ForeignKey(verbose_name='Nh\xe0 s\u1ea3n xu\u1ea5t', blank=True, to='rnoc.ThietBi', null=True),
        ),
    ]
