# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rnoc', '0008_auto_20160611_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcnoss',
            name='tinh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rnoc.Tinh', verbose_name='T\u1ec9nh'),
        ),
        migrations.AlterField(
            model_name='doitac',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 436000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='duan',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 437000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='faultlibrary',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 445000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='lenh',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 446000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='mll',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 457000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='nguyennhan',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 18, 56, 20, 441000, tzinfo=utc), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='suco',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 18, 56, 20, 440000, tzinfo=utc), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='thaotaclienquan',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 443000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 435000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='tram',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 24, 18, 56, 20, 453000, tzinfo=utc), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
        migrations.AlterField(
            model_name='trangthai',
            name='ngay_gio_tao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 6, 25, 1, 56, 20, 442000), verbose_name='Ng\xe0y gi\u1edd t\u1ea1o'),
        ),
    ]
